# -*- coding: utf-8 -*-
#
# Copyright (C) 2024 CESNET.
#
# OARepo ecosystem is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#
# This file was automatically generated by the integration tests to show which changes
# were applied to the package.
"""Changes performed by oarepo-integration-tools."""

# the code below is json, so need to define a couple of aliases just to be sure
true = True
"""JSON True."""

false = False
"""JSON False."""

features_incorporated = '[{"name":"removed-webpack-aliases","base":"v12.0.12"}]'

oarepo_major_version = "12"

package_oarepo_version = "oarepo-12.0.12"

configuration = '{"name": "invenio-app-rdm", "oarepo": 12, "entrypoints": [{"remove": "*", "keep": [{"group": "invenio_assets.webpack", "name": "invenio_app_rdm_theme"}]}], "features": [{"name": "removed-webpack-aliases", "base": "v12.0.12"}], "package": "invenio-app-rdm", "invenio_version": "12.0.12", "version": "12.0.12"}'
